[tool.codeflash]
# All paths are relative to this pyproject.toml's directory.
module-root = "src"
tests-root = "tests"
benchmarks-root = "tests/benchmarks"
test-framework = "pytest"
ignore-paths = []
formatter-cmds = ["disabled"]
